# -*- coding: utf-8 -*-
"""personal_intro.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q11qKf5NNdenZpm5flHXCeEXbjVRviXd
"""

name = input("Enter your name: ")
age = input("Enter your age: ")
hobby = input("Enter your hobby: ")

# Displaying a friendly message
print(f"\nHello {name}! 👋")
print(f"You are {age} years old and you love {hobby}.")
print("That's awesome! Keep doing what you enjoy 😊")